disabled_rules:
  - trailing_whitespace

included:
  - LetterAvatarKit
  - LetterAvatarKitTests

line_length:
  - 110
  - 110

type_body_length:
  - 150
  - 150

identifier_name:
  excluded:
    - i
    - j
    - c
    - m
    - to
    - id
    