# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis
default_platform(:ios)

platform :ios do
  lane :test do
    swiftlint()
    scan(
      scheme: "LetterAvatarKit",
      clean: true
    )
  end
end
